### ISSUE TITLE
YAML files cannot be accessed

### ISSUE THREAD

**Issue by jarvisjohnson** [caktus/aws-web-stacks#70]
All the links to the YAML files on s3 seem to be dead now or not publicly accessible.

Has the project been shut down?

**Comment by vkurup** [comment]
The project now generates YAML files instead of JSON, but that change has not been pushed to the master branch, or released yet. In the meantime, you can find [links to the JSON files on the master branch](https://github.com/caktus/aws-web-stacks/tree/master), or you can generate the YAML files locally from the develop branch by using the `make` command.
